version: "3.8"

services:
  hasura-finance-local:
    image: hasura/graphql-engine:v2.40.0
    container_name: hasura-finance-local
    restart: unless-stopped
    ports:
      - "8086:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: user
