version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: finance-system-postgres-local
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_system
    volumes:
      - finance_system_pg_data:/var/lib/postgresql/data

volumes:
  finance_system_pg_data:
